server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest
    username: postgres
    password: DBMira
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Rest-n'-peace

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true